"use client";

import { useEffect, useState, useTransition } from "react";
import { X } from "lucide-react";
import { loadSupplierProductHistoryAction } from "@/app/precificacoes-salvas/actions";
import { formatMoney, formatPercent } from "@/lib/format";
import type { ScenarioKey, SupplierProductAnalytics } from "@/lib/data/supplier-analytics";
import type { ProductPricingHistoryResult } from "@/lib/data/saved-pricing-analytics";
import { PricingDetailButton } from "./pricing-detail-button";

const labels: Record<ScenarioKey, string> = { ML_CLASSICO: "Mercado Livre Clássico", ML_PREMIUM: "Mercado Livre Premium", SHOPEE: "Shopee", AMAZON: "Amazon" };
const regionLabels = { SP: "São Paulo", SUL_SUDESTE: "Sul / Sudeste", NORTE_NORDESTE: "Norte / Nordeste" } as const;

function ProductHistoryModal({ product, initial, onClose }: { product: SupplierProductAnalytics; initial: ProductPricingHistoryResult; onClose: () => void }) {
  const [result, setResult] = useState(initial), [pending, startTransition] = useTransition();
  useEffect(() => { const close = (event: KeyboardEvent) => { if (event.key === "Escape") onClose(); }, previousOverflow = document.body.style.overflow; document.addEventListener("keydown", close); document.body.style.overflow = "hidden"; return () => { document.removeEventListener("keydown", close); document.body.style.overflow = previousOverflow; }; }, [onClose]);
  const pages = Math.max(1, Math.ceil(result.total / result.pageSize));
  const goTo = (page: number) => startTransition(async () => { const next = await loadSupplierProductHistoryAction(product.id, page); if (next) setResult(next); });
  return <div className="supplier-history-backdrop" role="presentation" onMouseDown={(event) => { if (event.target === event.currentTarget) onClose(); }}><section className="supplier-history-modal" role="dialog" aria-modal="true" aria-labelledby="supplier-history-title"><header><div><span>Histórico de precificações</span><h2 id="supplier-history-title">{product.sku} · {product.name}</h2><p>{result.total} registro{result.total === 1 ? "" : "s"} salvo{result.total === 1 ? "" : "s"}, do mais recente para o mais antigo.</p></div><button autoFocus type="button" onClick={onClose} aria-label="Fechar histórico"><X size={18} /></button></header>
    {result.items.length ? <div className="supplier-history-list"><div className="supplier-history-row head"><span>Data</span><span>Responsável</span><span>Canal</span><span>Preço</span><span>Frete</span><span>Margem</span><span>Ação</span></div>{result.items.map((item) => <article className="supplier-history-row" key={item.id}><span>{new Date(item.createdAt).toLocaleString("pt-BR", { dateStyle: "short", timeStyle: "short" })}<small>{regionLabels[item.region]}</small></span><span>{item.createdByName}</span><span>{item.marketplace}<small>{item.listingType === "PREMIUM" ? "Premium" : item.listingType === "CLASSICO" ? "Clássico" : "Padrão"}</small></span><span>{formatMoney(item.price)}</span><span>{formatMoney(item.freight)}</span><span className="supplier-history-margin"><strong>{formatMoney(item.marginValue)}</strong><small>{formatPercent(item.marginPercent)}</small></span><span><PricingDetailButton id={item.id} compact /></span></article>)}</div> : <div className="empty-inline">Nenhuma precificação salva para este produto.</div>}
    <nav className="history-pagination"><button type="button" disabled={pending || result.page <= 1} onClick={() => goTo(result.page - 1)}>Anterior</button><span>Página {result.page} de {pages}</span><button type="button" disabled={pending || result.page >= pages} onClick={() => goTo(result.page + 1)}>Próxima</button></nav>
  </section></div>;
}

export function SupplierProductTable({ products, region }: { products: SupplierProductAnalytics[]; region: "SP" | "SUL_SUDESTE" | "NORTE_NORDESTE" }) {
  const [selected, setSelected] = useState<{ product: SupplierProductAnalytics; history: ProductPricingHistoryResult } | null>(null), [loadingId, setLoadingId] = useState(""), [, startTransition] = useTransition();
  const open = (product: SupplierProductAnalytics) => { setLoadingId(product.id); startTransition(async () => { const history = await loadSupplierProductHistoryAction(product.id); setLoadingId(""); if (history) setSelected({ product, history }); }); };
  const scenarioKeys = Object.keys(labels) as ScenarioKey[];
  return <><div className="supplier-product-table"><div className="supplier-product-row head"><span>Produto</span>{scenarioKeys.map((key) => <span key={key}>{labels[key].replace("Mercado Livre ", "ML ")}</span>)}</div>{products.map((product) => <div className="supplier-product-row" key={product.id}><span><button type="button" className="supplier-product-open" disabled={loadingId === product.id} onClick={() => open(product)}><strong>{product.sku}</strong><small>{loadingId === product.id ? "Carregando histórico..." : product.name}</small></button><small>{product.active ? `Custo ${formatMoney(String(product.cost))}` : "Extinto"}</small>{product.pending && <em>Reprecificação pendente</em>}</span>{scenarioKeys.map((key) => { const metric = product.scenarios[key]; return <span className="supplier-margin-cell" tabIndex={metric ? 0 : undefined} key={key}>{metric ? <><strong>{formatMoney(String(metric.marginValue))}</strong><small>{formatPercent(String(metric.marginPercent))}</small><small>Preço {formatMoney(String(metric.price))}</small><span className="supplier-margin-tooltip"><b>Margem: {formatMoney(String(metric.marginValue))} ({formatPercent(String(metric.marginPercent))})</b><br />Preço: {formatMoney(String(metric.price))}<br />Frete: {formatMoney(String(metric.shipping))}<br />Comissão: {formatMoney(String(metric.commission))}<br />Tarifa: {formatMoney(String(metric.fixedFee))}<br />Rebate: {formatMoney(String(metric.rebate))}<br />Região: {regionLabels[region]}<br />{new Date(metric.createdAt).toLocaleString("pt-BR")}</span></> : "Sem dados"}</span>; })}</div>)}</div>{selected && <ProductHistoryModal product={selected.product} initial={selected.history} onClose={() => setSelected(null)} />}</>;
}
