"use client";

import { useEffect, useState } from "react";
import { X } from "lucide-react";
import { formatMoney, formatPercent } from "@/lib/format";
import type { ScenarioKey, SupplierProductAnalytics } from "@/lib/data/supplier-analytics";

const labels:Record<ScenarioKey,string>={ML_CLASSICO:"Mercado Livre Clássico",ML_PREMIUM:"Mercado Livre Premium",SHOPEE:"Shopee",AMAZON:"Amazon"};
const regionLabels={SP:"São Paulo",SUL_SUDESTE:"Sul / Sudeste",NORTE_NORDESTE:"Norte / Nordeste"} as const;

function ProductHistoryModal({product,onClose}:{product:SupplierProductAnalytics;onClose:()=>void}){
 useEffect(()=>{const close=(event:KeyboardEvent)=>{if(event.key==="Escape")onClose();},previousOverflow=document.body.style.overflow;document.addEventListener("keydown",close);document.body.style.overflow="hidden";return()=>{document.removeEventListener("keydown",close);document.body.style.overflow=previousOverflow;};},[onClose]);
 return <div className="supplier-history-backdrop" role="presentation" onMouseDown={event=>{if(event.target===event.currentTarget)onClose();}}><section className="supplier-history-modal" role="dialog" aria-modal="true" aria-labelledby="supplier-history-title"><header><div><span>Histórico de precificações</span><h2 id="supplier-history-title">{product.sku} · {product.name}</h2><p>{product.pricingHistory.length} registro{product.pricingHistory.length===1?"":"s"} salvo{product.pricingHistory.length===1?"":"s"}, do mais recente para o mais antigo.</p></div><button autoFocus type="button" onClick={onClose} aria-label="Fechar histórico"><X size={18}/></button></header>{product.pricingHistory.length?<div className="supplier-history-list"><div className="supplier-history-row head"><span>Data</span><span>Canal</span><span>Preço</span><span>Frete</span><span>Margem</span></div>{product.pricingHistory.map(item=><article className="supplier-history-row" key={item.id}><span>{new Date(item.createdAt).toLocaleString("pt-BR",{dateStyle:"short",timeStyle:"short"})}<small>{regionLabels[item.region]}</small></span><span>{labels[item.scenario]}</span><span>{formatMoney(String(item.price))}</span><span>{formatMoney(String(item.shipping))}</span><span className="supplier-history-margin"><strong>{formatMoney(String(item.marginValue))}</strong><small>{formatPercent(String(item.marginPercent))}</small></span></article>)}</div>:<div className="empty-inline">Nenhuma precificação salva para este produto.</div>}</section></div>;
}

export function SupplierProductTable({products,region}:{products:SupplierProductAnalytics[];region:"SP"|"SUL_SUDESTE"|"NORTE_NORDESTE"}){
 const [selected,setSelected]=useState<SupplierProductAnalytics|null>(null),scenarios=(Object.keys(labels) as ScenarioKey[]);
 return <><div className="supplier-product-table"><div className="supplier-product-row head"><span>Produto</span>{scenarios.map(key=><span key={key}>{labels[key].replace("Mercado Livre ","ML ")}</span>)}</div>{products.map(product=><div className="supplier-product-row" key={product.id}><span><button type="button" className="supplier-product-open" onClick={()=>setSelected(product)}><strong>{product.sku}</strong><small>{product.name}</small></button><small>{product.active?`Custo ${formatMoney(String(product.cost))}`:"Extinto"}</small>{product.pending&&<em>Reprecificação pendente</em>}</span>{scenarios.map(key=>{const metric=product.scenarios[key];return <span className="supplier-margin-cell" tabIndex={metric?0:undefined} key={key}>{metric?<><strong>{formatMoney(String(metric.marginValue))}</strong><small>{formatPercent(String(metric.marginPercent))}</small><small>Preço {formatMoney(String(metric.price))}</small><span className="supplier-margin-tooltip"><b>Margem: {formatMoney(String(metric.marginValue))} ({formatPercent(String(metric.marginPercent))})</b><br/>Preço: {formatMoney(String(metric.price))}<br/>Frete: {formatMoney(String(metric.shipping))}<br/>Comissão: {formatMoney(String(metric.commission))}<br/>Tarifa: {formatMoney(String(metric.fixedFee))}<br/>Rebate: {formatMoney(String(metric.rebate))}<br/>Região: {regionLabels[region]}<br/>{new Date(metric.createdAt).toLocaleString("pt-BR")}</span></>:"Sem dados"}</span>})}</div>)}</div>{selected&&<ProductHistoryModal product={selected} onClose={()=>setSelected(null)}/>}</>;
}
