import Link from "next/link";
import type { Route } from "next";
import { MarketplaceBrand } from "./marketplace-brand";
import { formatMoney, formatPercent } from "@/lib/format";
import type { AnalyticsRegion, ScenarioKey, SupplierAnalytics, SupplierProductAnalytics } from "@/lib/data/supplier-analytics";
import type { MarketplaceKey } from "@/domain/pricing/types";
import { PrintButton } from "./print-button";

const labels: Record<ScenarioKey,string> = { ML_CLASSICO:"ML Clássico", ML_PREMIUM:"ML Premium", SHOPEE:"Shopee", AMAZON:"Amazon" };
const scenarios = Object.keys(labels) as ScenarioKey[];
const brand = (key:ScenarioKey):MarketplaceKey => key.startsWith("ML_") ? "MERCADO_LIVRE" : key as MarketplaceKey;
const newestMetric = (product:SupplierProductAnalytics) => Object.values(product.scenarios).toSorted((a,b)=>b.createdAt.localeCompare(a.createdAt))[0];
const reportUrl = (supplierId:string, values:Record<string,string|number|boolean|undefined>) => { const params=new URLSearchParams(); for(const [key,value] of Object.entries(values)) if(value!==undefined&&value!==false&&value!=="") params.set(key,String(value===true?1:value)); return `/fornecedores/${supplierId}?${params}` as Route; };
export type SupplierAnalyticsFilters = { query:string; includeInactive:boolean; region:AnalyticsRegion; scenario:"ALL"|ScenarioKey; coverage:"ALL"|"WITH"|"WITHOUT"; pending:"ALL"|"YES"|"NO"; age:"ALL"|"30"|"60"|"90"; margin:"ALL"|"BAD"|"ACCEPTABLE"; sort:"product"|"cost"|"price"|"marginValue"|"marginPercent"|"date"|"status"; direction:"asc"|"desc"; page:number };

export function SupplierAnalyticsView({supplier,analytics,filters}:{supplier:{id:string;name:string};analytics:SupplierAnalytics;filters:SupplierAnalyticsFilters}){
 // Server-rendered report timestamp; stable for this response and intentionally not interactive state.
 // eslint-disable-next-line react-hooks/purity
 const now=Date.now(); let filtered=analytics.products.filter(product=>{ if(!filters.includeInactive&&!product.active)return false; if(filters.query&&!`${product.sku} ${product.childSkus.join(" ")} ${product.name} ${product.manufacturerCode??""}`.toLowerCase().includes(filters.query.toLowerCase()))return false; const metrics=filters.scenario==="ALL"?Object.values(product.scenarios):product.scenarios[filters.scenario]?[product.scenarios[filters.scenario]!]:[]; if(filters.coverage==="WITH"&&!metrics.length)return false; if(filters.coverage==="WITHOUT"&&metrics.length)return false; if(filters.pending==="YES"&&!product.pending)return false; if(filters.pending==="NO"&&product.pending)return false; if(filters.age!=="ALL"&&(!metrics.length||metrics.every(metric=>now-new Date(metric.createdAt).getTime()<=Number(filters.age)*86400000)))return false; if(filters.margin==="BAD"&&(!metrics.length||Math.min(...metrics.map(metric=>metric.marginPercent))>=.09))return false; if(filters.margin==="ACCEPTABLE"&&(!metrics.length||Math.max(...metrics.map(metric=>metric.marginPercent))<.09))return false; return true; });
 const direction=filters.direction==="asc"?1:-1; filtered=filtered.toSorted((a,b)=>{const am=newestMetric(a),bm=newestMetric(b); const values={product:[`${a.sku} ${a.name}`,`${b.sku} ${b.name}`],cost:[a.cost,b.cost],price:[am?.price??-Infinity,bm?.price??-Infinity],marginValue:[am?.marginValue??-Infinity,bm?.marginValue??-Infinity],marginPercent:[am?.marginPercent??-Infinity,bm?.marginPercent??-Infinity],date:[am?.createdAt??"",bm?.createdAt??""],status:[Number(a.active),Number(b.active)]} as const; const [av,bv]=values[filters.sort]; return (typeof av==="number"?av-Number(bv):String(av).localeCompare(String(bv),"pt-BR",{numeric:true}))*direction;});
 const pageSize=20,total=filtered.length,pages=Math.max(1,Math.ceil(total/pageSize)),page=Math.min(filters.page,pages),products=filtered.slice((page-1)*pageSize,page*pageSize); const shared={query:filters.query,region:filters.region,inactive:filters.includeInactive,scenario:filters.scenario,coverage:filters.coverage,pending:filters.pending,age:filters.age,margin:filters.margin,sort:filters.sort,direction:filters.direction};
 const below=analytics.products.filter(p=>p.active&&Object.values(p.scenarios).some(m=>m.marginPercent<.09)).length,stale=analytics.products.filter(p=>p.active&&Object.values(p.scenarios).some(m=>now-new Date(m.createdAt).getTime()>90*86400000)).length;
 return <>
 <div className="supplier-report-actions"><Link className="secondary-button" href={`/fornecedores/${supplier.id}/editar`}>Editar fornecedor</Link><a className="secondary-button" href={`/fornecedores/${supplier.id}/exportar?region=${filters.region}&inactive=${filters.includeInactive?1:0}`}>Exportar CSV</a><PrintButton/></div>
 <form className="supplier-filter-grid"><input name="query" defaultValue={filters.query} placeholder="Buscar SKU pai, SKU filho, código ou nome"/><select name="region" defaultValue={filters.region}><option value="SP">São Paulo</option><option value="SUL_SUDESTE">Sul / Sudeste</option><option value="NORTE_NORDESTE">Norte / Nordeste</option></select><select name="scenario" defaultValue={filters.scenario}><option value="ALL">Todos os cenários</option>{scenarios.map(k=><option key={k} value={k}>{labels[k]}</option>)}</select><select name="coverage" defaultValue={filters.coverage}><option value="ALL">Com e sem precificação</option><option value="WITH">Com precificação</option><option value="WITHOUT">Sem precificação</option></select><select name="pending" defaultValue={filters.pending}><option value="ALL">Todas as pendências</option><option value="YES">Com pendência</option><option value="NO">Sem pendência</option></select><select name="age" defaultValue={filters.age}><option value="ALL">Qualquer data</option><option value="30">Mais de 30 dias</option><option value="60">Mais de 60 dias</option><option value="90">Mais de 90 dias</option></select><select name="margin" defaultValue={filters.margin}><option value="ALL">Todas as margens</option><option value="BAD">Abaixo de 9%</option><option value="ACCEPTABLE">9% ou mais</option></select><select name="sort" defaultValue={filters.sort}><option value="product">Ordenar por produto</option><option value="cost">Ordenar por custo</option><option value="price">Ordenar por preço</option><option value="marginValue">Ordenar por margem R$</option><option value="marginPercent">Ordenar por margem %</option><option value="date">Ordenar por data</option><option value="status">Ordenar por status</option></select><select name="direction" defaultValue={filters.direction}><option value="asc">Crescente</option><option value="desc">Decrescente</option></select><label><input type="checkbox" name="inactive" value="1" defaultChecked={filters.includeInactive}/> Incluir extintos</label><button className="secondary-button">Aplicar filtros</button></form>
 <section className="metric-grid supplier-metrics"><article className="metric-card"><span>Margem média geral</span><strong>{analytics.overall.count?formatPercent(String(analytics.overall.percent)):"Sem dados"}</strong><small>{analytics.overall.count?formatMoney(String(analytics.overall.value)):"Nenhuma precificação"}</small></article><article className="metric-card"><span>Cobertura</span><strong>{analytics.pricedProducts} de {analytics.activeProducts}</strong><small>{analytics.activeProducts?formatPercent(String(analytics.pricedProducts/analytics.activeProducts)):"0%"} dos produtos ativos</small></article><article className="metric-card"><span>Revisão necessária</span><strong>{analytics.pendingProducts}</strong><small>produtos pendentes</small></article><article className="metric-card"><span>Atenção</span><strong>{below}</strong><small>abaixo de 9% · {stale} desatualizados</small></article></section>
 <section className="scenario-summary">{scenarios.map(k=>{const m=analytics.averages[k];return <article className="wide-card" key={k}><h3><MarketplaceBrand marketplace={brand(k)} compact/>{labels[k]}</h3><strong>{m?formatPercent(String(m.percent)):"Sem dados"}</strong><small>{m?`${formatMoney(String(m.value))} · ${m.count} observações`:"Nenhuma precificação"}</small></article>})}</section>
 <section className="supplier-rankings"><article className="wide-card"><span>Maior margem em R$</span><strong>{analytics.topValue?.sku??"Sem dados"}</strong><small>{analytics.topValue?.name}</small></article><article className="wide-card"><span>Maior margem percentual</span><strong>{analytics.topPercent?.sku??"Sem dados"}</strong><small>{analytics.topPercent?.name}</small></article><article className="wide-card"><span>Menor margem</span><strong>{analytics.lowest?.sku??"Sem dados"}</strong><small>{analytics.lowest?.name}</small></article></section>
 <section className="wide-card supplier-products"><div className="card-heading"><div><h2>Produtos e últimas precificações</h2><p>{total} produto{total===1?"":"s"} nos filtros atuais.</p></div></div><div className="supplier-product-table"><div className="supplier-product-row head"><span>Produto</span>{scenarios.map(k=><span key={k}>{labels[k]}</span>)}</div>{products.map(p=><div className="supplier-product-row" key={p.id}><span><strong>{p.sku}</strong><small>{p.name}</small><small>{p.active?`Custo ${formatMoney(String(p.cost))}`:"Extinto"}</small>{p.pending&&<em>Reprecificação pendente</em>}</span>{scenarios.map(k=>{const m=p.scenarios[k];return <span className="supplier-margin-cell" tabIndex={m?0:undefined} key={k}>{m?<><strong>{formatMoney(String(m.marginValue))}</strong><small>{formatPercent(String(m.marginPercent))}</small><small>Preço {formatMoney(String(m.price))}</small><span className="supplier-margin-tooltip"><b>Margem: {formatMoney(String(m.marginValue))} ({formatPercent(String(m.marginPercent))})</b><br/>Preço: {formatMoney(String(m.price))}<br/>Frete: {formatMoney(String(m.shipping))}<br/>Comissão: {formatMoney(String(m.commission))}<br/>Tarifa: {formatMoney(String(m.fixedFee))}<br/>Rebate: {formatMoney(String(m.rebate))}<br/>Região: {filters.region}<br/>{new Date(m.createdAt).toLocaleString("pt-BR")}</span></>:"Sem dados"}</span>})}</div>)}</div>{!products.length&&<div className="empty-inline">Nenhum produto corresponde aos filtros.</div>}<nav className="history-pagination" aria-label="Paginação dos produtos"><Link aria-disabled={page===1} href={reportUrl(supplier.id,{...shared,page:Math.max(1,page-1)})}>Anterior</Link><span>Página {page} de {pages}</span><Link aria-disabled={page===pages} href={reportUrl(supplier.id,{...shared,page:Math.min(pages,page+1)})}>Próxima</Link></nav></section>
 </>;
}
